PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Funkalphabet( Buchstabe text UNIQUE PRIMARY KEY, DIN text, Nato text);
INSERT INTO "Funkalphabet" VALUES('a','Anton','Alfa');
INSERT INTO "Funkalphabet" VALUES('ä','Ärger','Alfa-Echo');
INSERT INTO "Funkalphabet" VALUES('b','Berta','Bravo');
INSERT INTO "Funkalphabet" VALUES('c','Cäsar','Charlie');
INSERT INTO "Funkalphabet" VALUES('ch','Charlotte','Charlie-Hotel');
INSERT INTO "Funkalphabet" VALUES('d','Dora','Delta');
INSERT INTO "Funkalphabet" VALUES('e','Emil','Echo');
INSERT INTO "Funkalphabet" VALUES('f','Friedrich','Foxtrot');
INSERT INTO "Funkalphabet" VALUES('g','Gustav','Golf');
INSERT INTO "Funkalphabet" VALUES('h','Heinrich','Hotel');
INSERT INTO "Funkalphabet" VALUES('i','Ida','India');
INSERT INTO "Funkalphabet" VALUES('j','Julius','Juliett');
INSERT INTO "Funkalphabet" VALUES('k','Kaufmann','Kilo');
INSERT INTO "Funkalphabet" VALUES('l','Ludwig','Lima');
INSERT INTO "Funkalphabet" VALUES('m','Martha','Mike');
INSERT INTO "Funkalphabet" VALUES('n','Nordpol','November');
INSERT INTO "Funkalphabet" VALUES('o','Otto','Oscar');
INSERT INTO "Funkalphabet" VALUES('ö','Ökonom','Oscar-Echo');
INSERT INTO "Funkalphabet" VALUES('p','Paula','Papa');
INSERT INTO "Funkalphabet" VALUES('q','Quelle','Quebec');
INSERT INTO "Funkalphabet" VALUES('r','Richard','Romeo');
INSERT INTO "Funkalphabet" VALUES('s','Samuel','Sierra');
INSERT INTO "Funkalphabet" VALUES('sch','Schule','');
INSERT INTO "Funkalphabet" VALUES('ß','Eszett','Sierra-Sierra');
INSERT INTO "Funkalphabet" VALUES('t','Theodor','Tango');
INSERT INTO "Funkalphabet" VALUES('u','Ulrich','Uniform');
INSERT INTO "Funkalphabet" VALUES('ü','Übermut','Uniform-Echo');
INSERT INTO "Funkalphabet" VALUES('v','Viktor','Victor');
INSERT INTO "Funkalphabet" VALUES('w','Wilhlem','Whiskey');
INSERT INTO "Funkalphabet" VALUES('x','Xanthippe','X-Ray');
INSERT INTO "Funkalphabet" VALUES('y','Ypsilon','Yankee');
INSERT INTO "Funkalphabet" VALUES('z','Zacharias','Zulu');
COMMIT;

